version: '2'
services:
  :
    image: renren/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  renren-api:
    image: renren/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev